# Generated by Django 3.1.3 on 2020-11-18 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake', '0002_auto_20201118_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
