# Generated by Django 3.1.3 on 2020-11-18 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake', '0003_auto_20201118_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='', upload_to='fake/images'),
        ),
    ]
