# Generated by Django 3.1.3 on 2020-11-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake', '0004_auto_20201118_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
