# Generated by Django 3.1.3 on 2020-11-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake', '0005_product_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
